{% set name = "gwmemory" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gwmemory-{{ version }}.tar.gz
  sha256: 3f64183e6c30aa986ddf24aa62a49f2e351104c8653af7a321f7aa735d9f9392

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=3.7
    - numpy
    - scipy
    - sympy

test:
  imports:
    - gwmemory
    - gwmemory.waveforms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gwmemory/
  summary: Computing the non-linear energy memory for arbitrary gravitational waveforms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
