{% set name = "gwmemory" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gwmemory-{{ version }}.tar.gz
  sha256: 4acc34cc12b8388684a1540e792530890e00d8b79ceeb34501110851620b447c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=3.7
    - numpy
    - scipy
    - pandas

test:
  imports:
    - gwmemory
    - gwmemory.waveforms
  commands:
    - pip check
    - python -c "from gwmemory import angles; angles.load_gamma()"
  requires:
    - pip

about:
  home: https://pypi.org/project/gwmemory/
  summary: Computing the non-linear energy memory for arbitrary gravitational waveforms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
