{% set name = "gwmemory" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gwmemory-{{ version }}.tar.gz
  sha256: d7eed06703208148fa27435e7bc03fd673b7d22defc48563ef53af0d225e50b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=3.7
    - numpy
    - scipy
    - pandas

test:
  imports:
    - gwmemory
    - gwmemory.waveforms
  commands:
    - pip check
    - python -c "from gwmemory import angles; angles.load_gamma()"
  requires:
    - pip

about:
  home: https://pypi.org/project/gwmemory/
  summary: Computing the non-linear energy memory for arbitrary gravitational waveforms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
